[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

#[colors.search.footer_bar]
#background = "#434c5e"
#foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SpaceMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true
