# Midnight Glacial Alacritty Theme
# Custom dark Nord variant — balanced, cool, high-contrast.

[colors.primary]
background = "#2E3440"    # Deep slate blue-gray background
foreground = "#ECEFF4"    # Bright text with crisp readability

[colors.normal]
black = "#3B4252"         # Slightly lighter than background
red = "#BF616A"           # Frosted crimson
green = "#A3BE8C"         # Subtle green for success indicators
yellow = "#EBCB8B"        # Warm yellow accent
blue = "#5E81AC"          # Muted blue for structure
magenta = "#B48EAD"       # Soft purple tone
cyan = "#88C0D0"          # Frosty cyan
white = "#E5E9F0"         # Light neutral

[colors.bright]
black = "#4C566A"         # Brighter shadow gray
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#ECEFF4"

[colors.cursor]
cursor = "#88C0D0"
text = "#2E3440"

[colors.selection]
background = "#434C5E"
text = "#ECEFF4"

[colors.search.matches]
background = "#8FBCBB"
foreground = "#2E3440"

[colors.vi_mode_cursor]
cursor = "#81A1C1"
text = "#2E3440"

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SpaceMono Nerd Font"
style = "Bold Italic"

[window]
opacity = 0.92            # Subtle trans

