#!/bin/sh

# Basic settings
bspc config border_width 2          # Set border width of windows
bspc config window_gap 12           # Set gap between windows

# Set the desktop wallpaper
feh --bg-fill $HOME/Pictures/desktop_wallpaper/icestations/logo/logo_desktop.png

# Detect monitors and assign workspaces
laptop_monitor="eDP-1"
desktop_monitor=$(xrandr --query | grep 'DP-[1-4]' | grep ' connected' | cut -d' ' -f1 | head -n 1)

if [ -n "$desktop_monitor" ]; then
    # Desktop mode: Assign workspaces to desktop and laptop monitors
    bspc monitor $desktop_monitor -d 1 2 3 4
    bspc monitor $laptop_monitor -d 5
    
else
    # Laptop mode: Assign all workspaces to laptop monitor
    bspc monitor $laptop_monitor -d 1 2 3 4
fi

# Rule for Firefox
bspc rule -a Firefox desktop='^1'

# Rule for Terminator
bspc rule -a Terminator desktop='^1'

# Default split direction for vertical layout
bspc config initial_polarity first_child
bspc config automatic_scheme longest_side

# Start sxhkd for keybindings
pkill sxhkd  # Kill any existing instance
sxhkd >> /var/log/sxhkd.log 2>&1 &

# Launch Polybar, using default config location ~/.config/polybar/config
~/.config/polybar/launch.sh &
