#!/usr/bin/env sh

#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar on every monitor
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload desk -c ~/.config/polybar/desk.ini &
done


[colors]
background = #2E3440  ;Nord0 - Polar Night
foreground = #D8DEE9  ;Nord4 - Snow Storm
linecolor = #88C0D0  ;Nord8 - Frost
bordercolor = #3B4252 ;Nord1 - Polar Night
accent = #81A1C1    ;Nord9 - Frost

[settings]
screenchange-reload = true

[global/wm]
margin-top = 2
margin-bottom = 2

#;Top Bar Configuration
[bar/top]
enable-ipc = true
width = 100%
height = 24
background = ${colors.background}
foreground = ${colors.foreground}
#Additional style settings (borders, padding, etc.)
font-0 = "SpaceMono Nerd Font:size=10;1"

...

Modules to be displayed on the top bar
modules-left = bspwm
modules-right = date
k
Scroll actions
scroll-up = bspwm-deskprev
scroll-down = bspwm-desknext

#;Bottom Bar Configuration (inherits settings from top bar)
[bar/bottom]
inherit = bar/top
#monitor = ${env:MONITOR:eDP-1}
bottom = true
Modules for the bottom bar
modules-left = bspwm
modules-center =
modules-right = github fs-root date power-menu

#Module Configurations (only necessary modules are included)
...

[module/bspwm]
type = internal/bspwm
enable-scroll = false
format = <label-state> <label-mode>
Workspace icons configuration
...

[module/pulseaudio]
type = internal/pulseaudio
#;Configuration for the module
format-click = exec pavucontrol

[module/system-bluetooth-bluetoothctl]
type = custom/script
exec = ~/.config/polybar/scripts/system-bluetooth-bluetoothctl.sh
tail = true
click-left = ~//.config/polybar/scripts/system-bluetooth-bluetoothctl.sh --toggle &

[module/bspwm]
type = internal/bspwm
bspwm-socket-path = /tmp/bspwm0_0-socket

[module/date]
type = internal/date
date = "%Y-%m-%d"
time = "%H:%M"
format = "%date% %time%"

