## bash aliases

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

#install the most recent discord download 
alias install_discord_update='latest_discord_deb=$(find ~/Downloads/firefox/ -maxdepth 1 -type f -name "discord*.deb" -printf "%T@ %p\n" | sort -n | tail -1 | awk "{print \$2}"); sudo dpkg -i "$latest_discord_deb"'

